### ISSUE TITLE
Cold start and progress updates

### ISSUE THREAD

**Issue by bamochri** [ayrwag/chrome-whisper#1]
Noticed:
1. A cold start issue after dragging an audio file and before any progress is shown. Had to wait 30secs before any progress appeared
2. Percentage in progress next to `Uploaded` has too many decimal points and goes beyond the dialog edge
3. Would suggest showing each step when it happens and corresponding progress % update (i.e. only showing label `Transcribing` and corresponding progress % AFTER the `Uploading` step has been completed)

**Comment by ayrwag** [comment]
> Noticed:
> 
> 1. A cold start issue after dragging an audio file and before any progress is shown. Had to wait 30secs before any progress appeared
> 2. Percentage in progress next to `Uploaded` has too many decimal points and goes beyond the dialog edge
> 3. Would suggest showing each step when it happens and corresponding progress % update (i.e. only showing label `Transcribing` and corresponding progress % AFTER the `Uploading` step has been completed)

### Noted. Here's what I've changed (Commit 72d8a883b75d5002973ee11dc7edc99dd8819a61):

1. Added a more descriptive label: "CPU cold start. AI model is loading" in the place of "loading" when there is a cold start
2. Removed unnecessary decimals from the percentage using Math.floor.
3. Made "Transcribing" step only display after the file has successfully uploaded ✅.
