### ISSUE TITLE
Audio files with long title shift audio player and come off the screen

### ISSUE THREAD

**Issue by bamochri** [ayrwag/chrome-whisper#2]
Uploading an audio file with a long title shifts the audio player and comes off the screen

<img width="302" alt="Screenshot 2024-04-17 at 19 42 40" src="https://github.com/ayrwag/chrome-whisper/assets/91987687/c318bbe4-fd60-45eb-9c37-8295424513f0">

**Comment by ayrwag** [comment]
Resolved long filenames extending past the page in a recent commit
## File with long title
![image](https://github.com/ayrwag/chrome-whisper/assets/139829598/ac95a912-8576-440f-b32d-b329a0fb227a)
