### ISSUE TITLE
Include audio file name in the transcription downloaded

### ISSUE THREAD

**Issue by bamochri** [ayrwag/chrome-whisper#3]
After successful transcription, clicking on download could let the user pick a name and location for the output file.

In the meantime, I would recommend including the audio file name in the output file name.

**Comment by ayrwag** [comment]
Resolved in [commit  72d8a883b75d5002973ee11dc7edc99dd8819a61](https://github.com/ayrwag/chrome-whisper/commit/d1011d61a7bb1770a966e35d77772b821aa3fc08) ✅
